name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clear GitHub Actions cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version

      - name: Clear npm cache
        run: npm cache verify

      - name: Install dependencies
        run: npm install

      - name: Fix Vite permission
        run: chmod +x node_modules/.bin/vite

      - name: Set Git config
        run: |
          git config --global user.email "francisjeevesjulayco@gmail.com"
          git config --global user.name "SirFtizgeral"

      - name: Build project
        run: npm run build

      - name: List files in dist
        run: ls -R ./dist  # List files in the dist directory

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist  # Ensure this path matches your build output path

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist  # Ensure this path matches the upload path

      - name: Set Git config
        run: |
          git config --global user.email "francisjeevesjulayco@gmail.com"
          git config --global user.name "SirFtizgeral"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ensure this path matches your build output path
